### ISSUE TITLE
인턴 채용과 관련된 모집 중인 해커톤 정보입니다.

### ISSUE THREAD

**Issue by JaeYeopHan** [jojoldu/junior-recruit-scheduler#1]
### MIDAS Challenge 2017
* 참가 접수 :: ~ 5월 8일 18:00
* 예선 대회 :: 5월 13일 10:00~14:00
* 본선 오리엔테이션 : 5월 20일 10:00
* 본선 대회 :: 5월 27일 ~ 5월 28일 (경제창조혁신센터)
* 특전 :: 우수 참가자에 한해 임원면접 기회 제공
[link](http://challenge.midasit.com/)

### NAVER HACK DAY
* 참가 접수 :: ~5월 11일 18:00
* 결과 발표 :: 5월 18일(개별 연락)
* 일정 :: 5월 25일 ~ 5월 26일(춘천), 25일 분당에서 함께 출발
* 내용 :: 희망 주제 선택하여 1박 2일 동안 멘토들과 해결하기
* 특전 :: 우수 참가자는 2017년 하계 인턴십 서류전형 면제
[link](https://form.office.naver.com/form/responseView.cmd?formkey=OGVjMDAxZDQtMjRmZC00Njk0LWJiMjEtNWIxN2U1YmY3N2Fh&sourceId=urlshare)

`README.md` 어느 부분에 넣어야 할 지 애매해서 일단 Issue에 등록해봅니다 :)

**Comment by jojoldu** [comment]
감사합니다 한재엽님! 반영하였습니다^^
