### ISSUE TITLE
English support

### ISSUE THREAD

**Issue by farzer** [jojoldu/junior-recruit-scheduler#157]

**Comment by ChungminPark** [comment]
Do you want to get a job in South Korera?

**Comment by jojoldu** [comment]
@farzer 
There are many English speaking students in Korea, so I think it would be good to have an English version.
But it's too hard for me to translate.
How about giving a PR?

**Comment by nulLeeKH** [comment]
I think I can translate for foreigners who want to get a job in Korea.

I'll start working from today.

**Comment by jojoldu** [comment]
https://github.com/jojoldu/junior-recruit-scheduler/blob/master/README-en_EN.md

Thanks @nulLeeKH
