### ISSUE TITLE
WATCHA

### ISSUE THREAD

**Issue by grohong** [jojoldu/junior-recruit-scheduler#175]
WATCHA(왓챠, 왓챠 플레이) 채용 공고가 있어 추천 합니다.

- [WATCHA 채용공고](http://www.frograms.com/joinus/)
- [잡플레닛 info](https://www.jobplanet.co.kr/companies/87452/reviews/%EC%99%93%EC%B1%A0)
- 기업리뷰: 3.8 점

**Comment by jojoldu** [comment]
@grohong 
확인이 늦었네요 ㅠ
해당 공고는 주니어 개발자 채용인지 확인이 어렵고,
공고 내용이 3년차이상의 경력자를 요구하는것 같아 등록하지 않겠습니다.

이슈 남겨주셔서 감사합니다 :)
