### ISSUE TITLE
저도 여기 저장소 후기 남기겠습니다!!

### ISSUE THREAD

**Issue by joont92** [jojoldu/junior-recruit-scheduler#184]
저 또한 @starrybleu 님 처럼 이번 이직시에 여기 저장소 도움을 많이 받았습니다!(정말 감사합니다)
간단하게나마 제 이직 후기를 작성해보았고, 혹시 좋은 사례가 될까 해서 공유해보고자 합니다..
적절하지 않으면 삭제하겠습니다 ㅠㅠ

<https://joont92.github.io/life/27%EC%82%B4-2%EB%B2%88%EC%A7%B8-%EC%9D%B4%EC%A7%81/>

다시한번 좋은 저장소를 만들어주셔서 감사드립니다.

**Comment by starrybleu** [comment]
멋지십니다! 공개하신 이력서가 깔끔하고 눈에 잘 들어오네요. 건승하세요 ㅎㅎ

**Comment by jojoldu** [comment]
오! 좋은 후기 감사합니다 :)
PR이 가능하시다면 PR로 보내주시면 반영하겠습니다 ^^

**Comment by joont92** [comment]
감사합니다!!!!!!
