### ISSUE TITLE
Backend FrontEnd뿐만 아니라 DataScience나 DeepLearning Engineer 신입도... 

### ISSUE THREAD

**Issue by ikarus-999** [jojoldu/junior-recruit-scheduler#205]
백, 프론트 말고 데이터 사이언스나 딥러닝, 데이터 사이언스 신입은 없나요??ㅜㅜㅜ

**Comment by lopun** [comment]
Riiid에서 신입도 모집하고 있습니다 :)
jh.ko@riiid.co로 연락주세요!

**Comment by jojoldu** [comment]
@ikarus-999 안녕하세요!
해당 분야 신입 채용 공고도 보이는대로 올리고 있습니다.
예전엔 데이터 전문 기업인 데이블 같은 기업의 채용 공고를 올리기도 했는데요.
최근엔 해당 분야 신입 채용 공고를 본게 없어 올리지 못하고 있습니다 :)
