### ISSUE TITLE
여름 스타트업 인턴 프로그램 링크 오류

### ISSUE THREAD

**Issue by jwonyLee** [jojoldu/junior-recruit-scheduler#217]
2019 Summer Coding - 여름 스타트업 인턴 프로그램 링크가 잘못 된 거 같습니다.
http://bitly.kr/aGqAr 으로 연결되는데 아래 이미지처럼 뜨네요
![image](https://user-images.githubusercontent.com/15073405/57081854-83497d00-6d30-11e9-9dc4-2fc7ce9d7c36.png)

**Comment by jojoldu** [comment]
@jwonyLee 안녕하세요 지원님 :)
제보 감사합니다!
해당 오류는 **서머코딩 홈페이지 자체의 문제**로 현재는 문제가 해결되었는지 정상 작동하고 있습니다!
이 이슈는 클로즈하겠습니다 :)

제보 다시한번 감사합니다!
