### ISSUE TITLE
트레바리 개발직군 채용 링크가 최신화가 되어 있지 않습니다.

### ISSUE THREAD

**Issue by inyong-e** [jojoldu/junior-recruit-scheduler#224]
실제 트레바리 홈페이지에서 들어간 개발직군 채용공고 내용과
여기서 들어간 채용공고 내용이 다릅니다.

여기 링크가 최신화가 되어있지 않은 것 같아요

**Comment by jojoldu** [comment]
@inyong-e 님 안녕하세요 :)
혹시 해당 트레바리 채용공고 링크가 있으시면 알려주실수있으실까요?
제가 확인했을때는 같은 공고 내용인듯해서요!

**Comment by inyong-e** [comment]
https://trevari.co.kr/recruit/show?id=00f8a4ad-ab04-49b6-a7d4-1373cef0b122

현재 트레바리는 강남 위워크로 이사를 했습니다.
그리고 기술스택도 변경사항이 있습니다.
확인 부탁드립니다 :)

**Comment by jojoldu** [comment]
@inyong-e 님 감사합니다 :) 해당 링크로 교체하겠습니다.!
