### ISSUE TITLE
Chinese Support

### ISSUE THREAD

**Issue by A0150315** [jojoldu/junior-recruit-scheduler#229]
😁 Because of lots of Chinese in Korea, I think the chinese version is necessary.

Or can I pull a request which is a chinese version Readme.md ?

**Comment by jojoldu** [comment]
@A0150315 
Thanks for the comments
I think it would be nice to have a translated version in Chinese as you say.
Please PR

**Comment by jojoldu** [comment]
https://github.com/jojoldu/junior-recruit-scheduler/pull/230
