### ISSUE TITLE
병역특례 옵션

### ISSUE THREAD

**Issue by JSpiner** [jojoldu/junior-recruit-scheduler#24]
주니어 개발자라면 병역특례를 노리시는분들이 많을것같은데, 병역특례만 묶어서 보여주는건 어떨까요?

**Comment by jojoldu** [comment]
오!? 좋은 아이디어 인것 같습니다!
혹시 관련해서 정보가 보이시면 풀리퀘스트 부탁드리겠습니다!

**Comment by JSpiner** [comment]
정리해서 풀리퀘스트 날려보겠습니다! 이 이슈는 닫아놓을게요.
