### ISSUE TITLE
삭제된(혹은 비공개된) 링크가 있습니다. 

### ISSUE THREAD

**Issue by br-kim** [jojoldu/junior-recruit-scheduler#317]
안녕하세요. 좋은 정보 모아두신 덕분에 도움을 많이 받고 있습니다.
최근에는 스프링 부트와 AWS를 사용해보는 책을 읽었는데 그 책을 쓰신분이
예전에 북마크해놓은 채용정보를 제공해주시는 분과 동일인이라는 것을 알고 놀랐어요. 

링크된 글들을 읽다보니 삭제되거나 비공개 된 것으로 보이는 링크가 있어서 이슈 올립니다.

용욱님의 스타트업 주의 사항
김남윤님의 신입 개발자 취업 도전기

이 두 개 링크는 확인이 안되더라구요.

다시 한번 노력에 감사드리고 별 건 아니지만 도움이 되었으면 하네요.

**Comment by jojoldu** [comment]
@br-kim 와! 감사합니다
아무래도 추천링크가 계속 늘어나다보니 놓치는 부분이 많네요 ㅠ
너무 큰 도움입니다!
해당 링크들은 바로 제거하겠습니다 ^^
다시한번 감사합니다!

**Comment by jojoldu** [comment]
@JinhaJjing 님 확인 감사합니다 :) 해당 링크 삭제하겠습니다.
