### ISSUE TITLE
본 저장소 이용 후기(여기 남겨도 되는걸까요..?)

### ISSUE THREAD

**Issue by starrybleu** [jojoldu/junior-recruit-scheduler#33]
안녕하세요, 저는 이번에 본 저장소를 애용하며 준비해, 좋은 회사에 합격하게 된 이한별이라고 합니다.

제 블로그에 저장소 후기 같은 내용 및 도움받은 내용을 조금 기록해보았는데, 이 저장소를 활용하여 성공한 사례를 공유드리고 싶어 이슈로 남기려고 합니다.
(저장소 이용 후기 내용보다는 개인적인 내용이 많지만 이 저장소에 있는 양질의 정보로 원하는 목표를 이루었다는 간증(?)이 되어 동기부여라도 되지 않을까 싶습니다.)

혹 적절하지 않은 '이슈'라면 미리 죄송하다는 말씀 드리며, 알려주시면 삭제하겠습니다.

http://lhb0517.tistory.com/entry/reviewofjojoldu

**Comment by jojoldu** [comment]
와! 내용 정말 감사합니다! 이런 내용은 얼마든지 환영입니다. 블로그는 저장소 본문에 추가해놓겠습니다.
제가 더 감사드립니다
정말 축하드립니다^^

**Comment by starrybleu** [comment]
앗, 환영해주시니 정말 감사드립니다. 혹시 이번 구직에 사용한 부끄러운 제 이력서나 포트폴리오가 궁금하신 분 계시면 개인정보 관련된 것만 편집해서 구글 독스 공유 문서로 오픈하겠습니다.

**Comment by YouDuk** [comment]
안녕하세요!

저도 취업 준비중인데, 비전공자라 이력서 작성이 캄캄합니다ㅠㅠ

혹시 이력서 공유 해주시면 감사하겠습니다!

2017년 8월 28일 (월) 오후 7:39, TerryLee <notifications@github.com>님이 작성:

**Comment by jojoldu** [comment]
짱짱 멋지십니다^^ 페이스북 페이지에도 블로그글 공유해서 많은 분들이 보실수있도록 하겠습니다

**Comment by starrybleu** [comment]
보잘 것 없는 제 글에 많은 관심 가져주셔서 감사합니다. 이력서, 포트폴리오는 잠깐의 편집을 하고 이따가 오늘 중으로 공유드리겠습니다!
