### ISSUE TITLE
인프런 프론트엔드 개발자 채용 관련

### ISSUE THREAD

**Issue by ag502** [jojoldu/junior-recruit-scheduler#398]
안녕하세요.
등록된 인프런 프론트엔드 개발자 채용이 (신입/경력)이 아닌 (경력) 인것 같습니다.
확인해주시면 감사하겠습니다!!

**Comment by jojoldu** [comment]
@ag502 님 안녕하세요!
인프런 FE는 신입은 없어졌으나 주니어경력직 (2~3년차)는 여전히 채용중이라서 유지중입니다 :) 
코멘트 수정해놓겠습니다!
