### ISSUE TITLE
2017년 SCPC 포스터입니다.

### ISSUE THREAD

**Issue by Jeju-Boobby** [jojoldu/junior-recruit-scheduler#5]
입상자는 대회 성적에 따라 삼성전자 채용 우대해준다는 내용도 있고,
총 상금이 1억원이라 관심있으신 분들이 있지 않을까 해서 이슈 등록해봅니다.

![scpc_leaflet_kor](https://cloud.githubusercontent.com/assets/17849556/26683640/7bf93074-471f-11e7-8b47-e3e5ef47383f.jpg)
![scpc_poster_kor](https://cloud.githubusercontent.com/assets/17849556/26683639/7bede494-471f-11e7-9656-c47403f3cafe.jpg)

**Comment by jojoldu** [comment]
오 감사합니다! 이런정보는 풀리퀘스트 주셔도 됩니다! 이슈 반영해놓겠습니다!
감사합니다^^

**Comment by jojoldu** [comment]
좀 더 상세하게 링크도 추가해주시면 제가 등록하기가 좀 더 편할것 같습니다^^;;
SCPC 사이트(코드그라운드)가 UI가 친절하지 않아 찾기가 어렵습니다 ㅠㅠ

**Comment by jojoldu** [comment]
등록되었습니다! 감사합니다 ^_^
