### ISSUE TITLE
김태곤님의 신입 프론트엔드 개발자를 위한 면접 조언

### ISSUE THREAD

**Issue by swtpumpkin** [jojoldu/junior-recruit-scheduler#99]
이 부분 링크 연결이 되지 않네요...
확인 바랍니다~

**Comment by luiseok** [comment]
해당 사이트 자체의 문제인것 같습니다.
태곤님 사이트에서 데이터베이스 문제로 게시글을 불러오지 못하고 있네요~

**Comment by swtpumpkin** [comment]
태곤님 사이트 전체가 로딩되지 않아서.... 업데이트가 필요해보여서요~ ㅎㅎ

**Comment by jojoldu** [comment]
안녕하세요!
지금 워드프레스 사이트 복구 된것 같습니다
(2018.01.15 08:00 기준)
